[tasks.start-client]
script = [
    "cd client/",
    "npm start"
]

[tasks.install-client]
script = [
    "cd client/",
    "npm install"
]

[tasks.start-server]
script = [
    "cargo build",
    "cargo run"
]
